
Neos:
  Neos:
    userInterface:
      editPreviewModes:
        seoView:
          isEditingMode: true
          isPreviewMode: false
          fusionRenderingPath: seoView
          title: 'Shel.SeoView:Main:editPreviewModes.seoView'
          position: 'after inPlace'
      translation:
        autoInclude:
          Shel.SeoView:
            - Main
            - 'NodeTypes/*'
    fusion:
      autoInclude:
        Shel.SeoView: true

  Fusion:
    defaultContext:
      Readability: 'Shel\SeoView\Eel\Helper\ReadabilityHelper'
